### ISSUE TITLE
Link to the newly created note is missing

### ISSUE THREAD

**Issue by pyrog** [osmlab/onosm.org#54]
Adding a new POI seem ok:
"_Thanks! An OpenStreetMap volunteer will add your data to the map soon."_

But the link to the note is not visible:
"_You can see the newly created note and watch for updates at this link:_ "

The javascript console display this error message:

Safari
```
[Error] TypeError: $("#category").val().join is not a function. (In '$("#category").val().join(", ")', '$("#category").val().join' is undefined)
	(fonction anonyme) (site.js:123)
	dispatch (jquery.min.js:3:10321)
```

Chrome and Firefox
```
Uncaught TypeError: $(...).val(...).join is not a function
    at HTMLButtonElement.<anonymous> (site.js:123)
    at HTMLButtonElement.dispatch (jquery.min.js:3)
    at HTMLButtonElement.q.handle (jquery.min.js:3)

```
Tested on **Safari**, **Chrome** and **Firefox** under macOS Sierra

**Comment by pyrog** [comment]
Regression since fb9814371eb1cc0dab1fb2b1e6cd18f6bc45a2a0. Remove `.join(…)` and the note will be created 😉 

But the link is never updated. See #35
